<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1b5a2635-b515-4281-808d-02013a8f6e39</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[1]/div[1]/lpx-navbar[1]/nav[1]/lpx-navbar-routes[1]/ul[1]/li[4]/lpx-sub-navbar[1]/ul[1]/li[2]/lpx-sub-navbar[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="lpx-inner-menu\\ hidden-in-hover-trigger"] &gt; [class="lpx-inner-menu-item"]:nth-child(2) [class="lpx-menu-item-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'\u8acb\u6c42\u9805\u76ee\u30de\u30b9\u30bf')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Billing Items"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>請求項目マスタ</value>
        <webElementGuid>28af00cb-fb2a-41da-b4ce-72c4846ce8a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>