<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af1dee27-67a5-443b-a8d5-16e1ad4105d1</elementGuidId>
    <imagePath></imagePath>
    <name>select_estimate-item-group-category</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ngb-modal-window[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[4]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="mb-3"] &gt; #estimate-item-group-category</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'estimate-item-group-category')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#estimate-item-group #estimate-item-group-category</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>estimate-item-group-category</value>
        <webElementGuid>370d127c-d494-4e23-a260-af59de044969</webElementGuid>
    </webElementProperties>
</WebElementEntity>