<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb97e4f1-b239-424b-b11a-b34be354553b</elementGuidId>
    <imagePath></imagePath>
    <name>select_estimate_item_group_category</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ngb-modal-window[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[4]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="mb-3"] &gt; #estimate-item-group-category</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'estimate-item-group-category')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#estimate-item-group #estimate-item-group-category</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>estimate-item-group-category</value>
        <webElementGuid>28af00cb-fb2a-41da-b4ce-72c4846ce8a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>