<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d7f4511b-14f9-4eb1-925b-ac62f51a3f3c</elementGuidId>
    <imagePath></imagePath>
    <name>button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-place[1]/abp-page[1]/div[1]/abp-page-toolbar-container[1]/div[1]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-primary\\ ms-1\\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'\u65b0\u3057\u3044\u5834\u6240')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="New Place"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>新しい場所</value>
        <webElementGuid>28af00cb-fb2a-41da-b4ce-72c4846ce8a7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>28af00cb-fb2a-41da-b4ce-72c4846ce8a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>