<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>88c93253-b5ee-417d-b34e-2b384c5c0c4c</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[3]/app-footer[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="lpx-footbar"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text=/^Copyright \xa9 2024 PortX$/ &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>