<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8d333af8-e452-4dc1-98f6-a5d998d275a5</elementGuidId>
    <imagePath></imagePath>
    <name>input_flexswitchcheckchecked_3a115228_f2d8_6320_e9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-place[1]/abp-page[1]/div[3]/div[1]/table[1]/tbody[1]/tr[4]/td[4]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#flexSwitchCheckChecked-3a115228-f2d8-6320-e91a-81ea435558e3</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'flexSwitchCheckChecked-3a115228-f2d8-6320-e91a-81ea435558e3') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="\uf4ca test5 kawasaki"i] &gt;&gt; internal:role=checkbox</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>flexSwitchCheckChecked-3a115228-f2d8-6320-e91a-81ea435558e3</value>
        <webElementGuid>d62dd4a4-fddc-4935-95b2-b757e584328f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>d62dd4a4-fddc-4935-95b2-b757e584328f</webElementGuid>
    </webElementProperties>
</WebElementEntity>