<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1583045-9203-4617-8b22-960be769374e</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-comparison-detail[1]/abp-page[1]/div[5]/div[1]/div[1]/div[2]/div[1]/app-compare-table[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[1]/form[1]/table[1]/tbody[1]/tr[2]/td[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(2) &gt; [class="sticky-col-left\ d-block\ pe-1"]:nth-child(1) [class="ng-star-inserted"]:nth-child(2) [type="checkbox"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>c134f6ae-b8a0-46fd-bb96-737cf5561be6</webElementGuid>
    </webElementProperties>
</WebElementEntity>