<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cf07f3f1-080a-463a-b2e1-8ed703359c2f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_ng_b_i_plqthang</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/b[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='https\:\/\/thangplq\.000webhostapp\.com\/author\/plqthang']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Đăng bởi plqthang')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Đăng bởi plqthang</value>
        <webElementGuid>9aa9058b-52f8-47e0-8a82-51c70aba208c</webElementGuid>
    </webElementProperties>
</WebElementEntity>