<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>04028be9-4ad1-49e6-b8ff-f7c5c9b7e878</elementGuidId>
    <imagePath></imagePath>
    <name>button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-supplier-detail[1]/abp-page[1]/div[4]/div[1]/div[2]/div[1]/app-frequent-project-supplier-user[1]/abp-page[1]/div[2]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ms-auto\ btn\ btn-primary"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'追加')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>追加</value>
        <webElementGuid>c134f6ae-b8a0-46fd-bb96-737cf5561be6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c134f6ae-b8a0-46fd-bb96-737cf5561be6</webElementGuid>
    </webElementProperties>
</WebElementEntity>