<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>802bdd35-1e8d-4ff3-b3b7-e4d2848f037a</elementGuidId>
    <imagePath></imagePath>
    <name>button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-session-detail[1]/div[1]/div[2]/div[3]/div[2]/app-empty-section[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(1) &gt; [class="section-box"] [class="btn\\ btn-primary\\ btn-sm\\ mt-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'\u56de\u7b54\u9805\u76ee\u3092\u7de8\u96c6')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="\u56de\u7b54\u9805\u76ee\u3092\u7de8\u96c6"i] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>回答項目を編集</value>
        <webElementGuid>28af00cb-fb2a-41da-b4ce-72c4846ce8a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>