<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>89d8fca2-fd33-4fca-bacc-8dc12e1938b1</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-session-detail[1]/div[1]/div[2]/div[3]/div[2]/app-fp-setting-item-type[1]/div[1]/div[2]/div[1]/div[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(5) [class="list-card-item\\ ng-star-inserted"]:nth-child(2) [class="bi\\ bi-plus-circle-fill\\ text-green\\ c-pointer"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(3) &gt; .section-box-body-content &gt; app-fp-setting-item-type &gt; .list-card &gt; div:nth-child(2) &gt; .card &gt; .card-body &gt; i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>