<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b8ab2f4e-1bd6-4da8-939a-5f648d138e79</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[1]/div[1]/lpx-navbar[1]/nav[1]/lpx-navbar-routes[1]/ul[1]/li[4]/lpx-sub-navbar[1]/ul[1]/li[8]/lpx-sub-navbar[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="lpx-inner-menu-item"]:nth-child(8) [class="lpx-menu-item-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'物流企業マスタ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>物流企業マスタ</value>
        <webElementGuid>c134f6ae-b8a0-46fd-bb96-737cf5561be6</webElementGuid>
    </webElementProperties>
</WebElementEntity>