<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>02e89a03-5082-42d0-90aa-bc1743a2993b</elementGuidId>
    <imagePath></imagePath>
    <name>h5_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ngb-modal-window[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/label[1]/div[1]/div[1]/h5[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-dark\ mb-0"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>