<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1187e322-fc7e-4e24-9584-dca5cf2e4024</elementGuidId>
    <imagePath></imagePath>
    <name>link_spot project management</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[1]/div[1]/lpx-navbar[1]/nav[1]/lpx-navbar-routes[1]/ul[1]/li[4]/lpx-sub-navbar[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="outer-menu-item"]:nth-child(4) &gt; lpx-sub-navbar &gt; [class="lpx-menu-item-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Spot project management')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="Spot project management"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Spot project management</value>
        <webElementGuid>370d127c-d494-4e23-a260-af59de044969</webElementGuid>
    </webElementProperties>
</WebElementEntity>