<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>facae5d0-23d5-48cd-b59f-918fc167862a</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ngb-datepicker[1]/div[2]/div[1]/ngb-datepicker-month[1]/div[6]/div[7]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="row"]:nth-child(6) &gt; [role="gridcell"]:nth-child(7) &gt; [class="btn-light\\ ng-star-inserted"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="31"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>