<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b755e2fa-2c9d-4e04-85a4-7e764eb41c50</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-supplier[1]/abp-page[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(2) &gt; [class="text-center ng-star-inserted"] &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="XXX123 "i] &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>370d127c-d494-4e23-a260-af59de044969</webElementGuid>
    </webElementProperties>
</WebElementEntity>