<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5b34822f-b01b-4507-99fa-74703b360ab1</elementGuidId>
    <imagePath></imagePath>
    <name>ngb_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ngb-modal-window[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="dialog"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>