<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e072597d-4d43-4a23-9d86-7baf312e6bca</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ng-dropdown-panel[1]/div[2]/div[2]/div[4]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#a1d8c57c35a4-3 &gt; [class="ng-option-label\\ ng-star-inserted"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="ISWNS (\u4f0a\u52e2\u6e7e\u5009\u5eab\u682a\u5f0f\u4f1a\u793e)"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>