<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>08f953ab-dff4-41ed-9e1a-9d0cc4661a5f</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ng-dropdown-panel[1]/div[2]/div[2]/div[3]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#af97df55c983-2 &gt; [class="ng-option-label\ ng-star-inserted"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>