<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>607e3d74-b08f-47b8-9ee2-d5a59cd091f1</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/aside[1]/div[1]/div[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.wp-block-search__button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'wp-block-search__button wp-element-button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>wp-block-search__button wp-element-button</value>
        <webElementGuid>3acd26de-5787-4655-8e7d-4fe8e1f057b4</webElementGuid>
    </webElementProperties>
</WebElementEntity>