<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>875adeec-5585-46b8-bed1-b409564134ef</elementGuidId>
    <imagePath></imagePath>
    <name>i_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/app-layout-empty[1]/div[1]/div[1]/app-frequent-project-reply-service[1]/abp-page[1]/div[2]/div[1]/div[1]/h1[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fa\ fa-arrow-left\ c-pointer"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>