<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ccdcb48a-1eff-46bf-bd54-71731863f879</elementGuidId>
    <imagePath></imagePath>
    <name>button_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-selection-item[1]/abp-page[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/app-selection-item-option[1]/div[2]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[type="button"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'\u4f5c\u6210')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-selection-item-option &gt;&gt; internal:role=button[name="\u4f5c\u6210"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>作成</value>
        <webElementGuid>d62dd4a4-fddc-4935-95b2-b757e584328f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>d62dd4a4-fddc-4935-95b2-b757e584328f</webElementGuid>
    </webElementProperties>
</WebElementEntity>