<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c12cfe08-ffc2-49a3-9808-00b71ce57aca</elementGuidId>
    <imagePath></imagePath>
    <name>input_flexswitchcheckchecked_3a0f452e_48ce_24a9_6f</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-selection-item[1]/abp-page[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/app-selection-item-option[1]/table[1]/tbody[1]/tr[2]/td[5]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#flexSwitchCheckChecked-3a0f452e-48ce-24a9-6f2f-e08f3fc704fa</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'flexSwitchCheckChecked-3a0f452e-48ce-24a9-6f2f-e08f3fc704fa') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="\uf013 02 \u5371\u967a\u54c1"i] &gt;&gt; internal:role=checkbox</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>flexSwitchCheckChecked-3a0f452e-48ce-24a9-6f2f-e08f3fc704fa</value>
        <webElementGuid>d62dd4a4-fddc-4935-95b2-b757e584328f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>d62dd4a4-fddc-4935-95b2-b757e584328f</webElementGuid>
    </webElementProperties>
</WebElementEntity>