<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6d28204a-bf9f-41fd-a234-f80369dc041d</elementGuidId>
    <imagePath></imagePath>
    <name>button_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-session-detail[1]/div[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(1) [class="section-box-body-footer"] &gt; [class="btn\ btn-primary\ btn-sm"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'レーン一覧')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>レーン一覧</value>
        <webElementGuid>4aa4377d-e00c-43c3-af41-a277e7a022e1</webElementGuid>
    </webElementProperties>
</WebElementEntity>