<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0afd875b-c28a-4bb5-a5f0-ec0397100e88</elementGuidId>
    <imagePath></imagePath>
    <name>button_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"] &gt; [class="btn\ btn-primary\ btn-sm"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'シートの追加')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>シートの追加</value>
        <webElementGuid>4aa4377d-e00c-43c3-af41-a277e7a022e1</webElementGuid>
    </webElementProperties>
</WebElementEntity>