<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>025f6bc1-c182-41bf-b67d-ebce905debab</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-supplier[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(1) &gt; [class="c-pointer"] &gt; [class="text-truncate"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>