<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f55e74a3-9f43-40be-913a-3d8896fbfe4f</elementGuidId>
    <imagePath></imagePath>
    <name>i_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-session-detail[1]/div[1]/div[2]/div[2]/div[2]/app-fp-setting-item-type[1]/div[1]/div[1]/div[1]/div[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="list-card-item\ ng-star-inserted"]:nth-child(1) [class="bi\ bi-plus-circle-fill\ text-green\ c-pointer"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>