<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3facd2b5-eb2a-4e42-8efc-720ea1ff9608</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-lane-condition[1]/abp-page[1]/div[2]/div[1]/h1[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fa\ fa-arrow-left\ c-pointer"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>