<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>90236f1b-2d8e-48fc-81d1-278eb8e70e91</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-lane-condition[1]/abp-page[1]/div[2]/div[1]/h1[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fa\ fa-arrow-left\ c-pointer"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>