<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2fa86cb0-745a-4fae-910c-d0b4eed254b6</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-session-detail[2]/div[1]/div[2]/div[2]/div[2]/app-fp-setting-item-type[1]/div[1]/div[3]/div[1]/div[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(2) [class="list-card-item\ ng-star-inserted"]:nth-child(3) [class="bi\ bi-plus-circle-fill\ text-green\ c-pointer"]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>