<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>19c83db1-e7e8-4a25-b3f9-f0292f1839ce</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-session[1]/abp-page[1]/div[3]/div[1]/div[2]/div[1]/app-frequent-project-comparison[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-truncate\ c-pointer"]:nth-child(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>