<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>20292c2e-a787-415e-b0f3-a11bbfb6fb66</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[1]/div[2]/div[2]/div[1]/app-frequent-project-detail[1]/abp-page[1]/div[3]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex-1"]:nth-child(1) &gt; [readonly="readonly"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>