<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9eb63233-394f-48ea-8458-7d762ce78df5</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ngb-modal-window[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/abp-tree[1]/nz-tree[1]/div[3]/div[1]/nz-tree-node[2]/nz-tree-node-title[1]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-tree-node-content-wrapper\ ant-tree-node-content-wrapper-close"] &gt; [class="ng-star-inserted"] [class="ng-star-inserted"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>